// src/lib/permissions.ts
export const PERMISSION_RESOURCES = {
  COMPANY: 'company',
  USER: 'user', 
  ROLE: 'role',
  HANDLING: 'handling',
  REPORT: 'report',
  SETTINGS: 'settings',
  BILLING: 'billing',
} as const

export const PERMISSION_ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update', 
  DELETE: 'delete',
  MANAGE: 'manage', // Todas as operações
  EXPORT: 'export',
  IMPORT: 'import',
} as const

// Permissões pré-definidas do sistema
export const SYSTEM_PERMISSIONS = {
  // Company
  COMPANY_MANAGE: `${PERMISSION_RESOURCES.COMPANY}.${PERMISSION_ACTIONS.MANAGE}`,
  COMPANY_READ: `${PERMISSION_RESOURCES.COMPANY}.${PERMISSION_ACTIONS.READ}`,
  COMPANY_UPDATE: `${PERMISSION_RESOURCES.COMPANY}.${PERMISSION_ACTIONS.UPDATE}`,
  
  // User Management
  USER_MANAGE: `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.MANAGE}`,
  USER_CREATE: `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.CREATE}`,
  USER_READ: `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.READ}`,
  USER_UPDATE: `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.UPDATE}`,
  USER_DELETE: `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.DELETE}`,
  
  // Roles
  ROLE_MANAGE: `${PERMISSION_RESOURCES.ROLE}.${PERMISSION_ACTIONS.MANAGE}`,
  ROLE_ASSIGN: `${PERMISSION_RESOURCES.ROLE}.assign`,
  
  // Handlings
  HANDLING_MANAGE: `${PERMISSION_RESOURCES.HANDLING}.${PERMISSION_ACTIONS.MANAGE}`,
  HANDLING_CREATE: `${PERMISSION_RESOURCES.HANDLING}.${PERMISSION_ACTIONS.CREATE}`,
  HANDLING_READ: `${PERMISSION_RESOURCES.HANDLING}.${PERMISSION_ACTIONS.READ}`,
  HANDLING_UPDATE: `${PERMISSION_RESOURCES.HANDLING}.${PERMISSION_ACTIONS.UPDATE}`,
  HANDLING_DELETE: `${PERMISSION_RESOURCES.HANDLING}.${PERMISSION_ACTIONS.DELETE}`,
  HANDLING_EXPORT: `${PERMISSION_RESOURCES.HANDLING}.${PERMISSION_ACTIONS.EXPORT}`,
  
  // Reports
  REPORT_VIEW: `${PERMISSION_RESOURCES.REPORT}.view`,
  REPORT_EXPORT: `${PERMISSION_RESOURCES.REPORT}.export`,
  
  // Settings
  SETTINGS_MANAGE: `${PERMISSION_RESOURCES.SETTINGS}.${PERMISSION_ACTIONS.MANAGE}`,
  
  // Billing
  BILLING_MANAGE: `${PERMISSION_RESOURCES.BILLING}.${PERMISSION_ACTIONS.MANAGE}`,
  BILLING_READ: `${PERMISSION_RESOURCES.BILLING}.${PERMISSION_ACTIONS.READ}`,
} as const

// Roles pré-definidas do sistema
export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'super_admin',
  COMPANY_ADMIN: 'company_admin',
  MANAGER: 'manager',
  USER: 'user',
  VIEWER: 'viewer',
} as const

// Mapeamento de roles para permissões
export const ROLE_PERMISSIONS_MAP = {
  [SYSTEM_ROLES.SUPER_ADMIN]: [
    SYSTEM_PERMISSIONS.COMPANY_MANAGE,
    SYSTEM_PERMISSIONS.USER_MANAGE,
    SYSTEM_PERMISSIONS.ROLE_MANAGE,
    SYSTEM_PERMISSIONS.HANDLING_MANAGE,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
    SYSTEM_PERMISSIONS.REPORT_EXPORT,
    SYSTEM_PERMISSIONS.SETTINGS_MANAGE,
    SYSTEM_PERMISSIONS.BILLING_MANAGE,
  ],
  
  [SYSTEM_ROLES.COMPANY_ADMIN]: [
    SYSTEM_PERMISSIONS.COMPANY_READ,
    SYSTEM_PERMISSIONS.COMPANY_UPDATE,
    SYSTEM_PERMISSIONS.USER_MANAGE,
    SYSTEM_PERMISSIONS.ROLE_ASSIGN,
    SYSTEM_PERMISSIONS.HANDLING_MANAGE,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
    SYSTEM_PERMISSIONS.REPORT_EXPORT,
    SYSTEM_PERMISSIONS.BILLING_READ,
  ],
  
  [SYSTEM_ROLES.MANAGER]: [
    SYSTEM_PERMISSIONS.USER_READ,
    SYSTEM_PERMISSIONS.HANDLING_MANAGE,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
    SYSTEM_PERMISSIONS.REPORT_EXPORT,
  ],
  
  [SYSTEM_ROLES.USER]: [
    SYSTEM_PERMISSIONS.HANDLING_CREATE,
    SYSTEM_PERMISSIONS.HANDLING_READ,
    SYSTEM_PERMISSIONS.HANDLING_UPDATE,
  ],
  
  [SYSTEM_ROLES.VIEWER]: [
    SYSTEM_PERMISSIONS.HANDLING_READ,
    SYSTEM_PERMISSIONS.REPORT_VIEW,
  ],
} as const